### PR TITLE
Update travis-ci config

### PR DESCRIPTION
**Pull request by ixti**

### CODE REVIEW

**Comment by abotalov** [comment]
Could you authorize with AppVeyor, add this project there and run a build with this PR?
I had some issue on Windows (https://github.com/bbatsov/rubocop/issues/3800) with one of changed cops.

**Comment by ixti** [comment]
@abotalov sure. and we need to make coveralls be less noizy

**Comment by ixti** [comment]
@abotalov added - although i must admit that appveyor's integration kinda terrible IMO

**Comment by ixti** [comment]
@abotalov is there a way to make enforce LF stay LF on Windows? I don't have any windows machines so i can't play around myself.

**Comment by abotalov** [comment]
@ixti You can revert commit https://github.com/httprb/form_data.rb/commit/a7565fc7883ed70071d6a9023efe4430446c69d6

This will fix AppVeyor but it will not make Rubocop passed if git config `core.autocrlf = true` which is a recommended setting in Github docs and Git Book.

I think it would be better to disable `Style/EndOfLine` cop as it doesn't work properly (bbatsov/rubocop#3401, bbatsov/rubocop#3800) and disabling will make default rake task work for others on Windows.

**Comment by ixti** [comment]
@abotalov I tend to either avoid rubocop on windows or removing that git config setting on appveyor. So far second thing seems more simple to me. Developers on windows can disable Style/EndOfLine on rubocop while developing.

**Pull request merged**
