### PR TITLE
Set Content-Type on non-file parts

### LINKED ISSUE #5: Setting Content-Type is not supported on non-file parts
From RFC 7578:
> **Each** part MAY have an (optional) "Content-Type" header field, which
> defaults to "text/plain".  If the contents of a file are to be sent,
> the file data SHOULD be labeled with an appropriate media type, if
> known, or "application/octet-stream".

Setting Content-Type for non-file parts is not currently supported.

### PR DESCRIPTION
**Pull request by ixti**
Resolves #5

### CODE REVIEW

**Comment by abotalov** [comment]
It seems to that this PR:
1. Sets Content-Type for all parts without allowing a user of the gem not to specify Content-Type.  
But RFC 7578 says that "Each part MAY have an (optional) "Content-Type" header field, which defaults to "text/plain"". So IMO this gem should either:
    * set Content-Type to text/plain for non-file parts
    * not add such header by default  
I think 2nd variant is better as API (see proposed variant below) becomes easier to use.
Regardless of the chosen solution, a user should be able to say that header shouldn't be added for a part (as this header is said to be optional in RFC).
2. Requires a user to implement a class that responds to `#mime_type` and `#to_s` to use the ability of overriding Content-Type.  
IMO a user of the gem shouldn't be required to implement some class. I think a library should provide such class directly.

All in all, I think API should allow usage like (fully backwards-compatible):
```ruby
form = HTTP::FormData.create({
  :username     => "ixti", # creates a part without Content-Type
  :avatar_file  => HTTP::FormData::File.new("/home/ixti/avatar.png")
})
```
```ruby
form = HTTP::FormData.create({
  :username     => HTTP::FormData::Part.new("ixti"), # creates a part without Content-Type, same as previous
  :avatar_file  => HTTP::FormData::File.new("/home/ixti/avatar.png")
})
```
```ruby
form = HTTP::FormData.create({
  :username     => HTTP::FormData::Part.new("ixti", :content_type => "application/json"), # creates a part with Content-Type
  :avatar_file  => HTTP::FormData::File.new("/home/ixti/avatar.png")
})
```

**Comment by ixti** [comment]
Hm. Then I misunderstood issue description. Agree with your proposals. Will try to fix PR as soon as will have time for that

**Comment by abotalov** [comment]
@ixti I can implement this feature myself too if you would like me to do it :smile:

**Comment by ixti** [comment]
@abotalov sure

**Comment by ixti** [comment]
Closing in favour of #10

**Pull request closed without merging**
